[theme]
base = "light"
primaryColor = "#FFCC00"
backgroundColor = "#F7F7F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111111"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false